export type ThemeColors = {
    primary: string
    planMode: string
    selection: string
    thinking: string
    success: string
    error: string
    info: string
    background: string
    surface: string
    dialogSurface: string
    thinkingBorder: string
    dimSeparator: string
}

export type Theme = {
    name: string
    colors: ThemeColors
}

export const THEMES: Theme[] = [
    // ── Dark themes ──────────────────────────────────────────────────────────

    {
        name: 'Obsidian',
        colors: {
            primary: '#e8c77a',
            planMode: '#c792ea',
            selection: '#e8c77a',
            thinking: '#c792ea',
            success: '#c3e88d',
            error: '#f07178',
            info: '#89ddff',
            background: '#0a0a0a',
            surface: '#141414',
            dialogSurface: '#060606',
            thinkingBorder: '#2a2a2a',
            dimSeparator: '#3d3d3d',
        },
    },
    {
        name: 'Tokyo Night',
        colors: {
            primary: '#7aa2f7',
            planMode: '#bb9af7',
            selection: '#7aa2f7',
            thinking: '#bb9af7',
            success: '#9ece6a',
            error: '#f7768e',
            info: '#7dcfff',
            background: '#1a1b26',
            surface: '#24283b',
            dialogSurface: '#13141e',
            thinkingBorder: '#363b54',
            dimSeparator: '#545c7e',
        },
    },
    {
        name: 'Dracula',
        colors: {
            primary: '#ff79c6',
            planMode: '#bd93f9',
            selection: '#bd93f9',
            thinking: '#ff79c6',
            success: '#50fa7b',
            error: '#ff5555',
            info: '#8be9fd',
            background: '#282a36',
            surface: '#343746',
            dialogSurface: '#1e1f29',
            thinkingBorder: '#44475a',
            dimSeparator: '#6272a4',
        },
    },
    {
        name: 'Gruvbox Dark',
        colors: {
            primary: '#fabd2f',
            planMode: '#d3869b',
            selection: '#b8bb26',
            thinking: '#d3869b',
            success: '#b8bb26',
            error: '#fb4934',
            info: '#83a598',
            background: '#1d2021',
            surface: '#282828',
            dialogSurface: '#141617',
            thinkingBorder: '#3c3836',
            dimSeparator: '#504945',
        },
    },
    {
        name: 'Nord',
        colors: {
            primary: '#88c0d0',
            planMode: '#b48ead',
            selection: '#81a1c1',
            thinking: '#b48ead',
            success: '#a3be8c',
            error: '#bf616a',
            info: '#88c0d0',
            background: '#2e3440',
            surface: '#3b4252',
            dialogSurface: '#242831',
            thinkingBorder: '#434c5e',
            dimSeparator: '#4c566a',
        },
    },
    {
        name: 'Catppuccin Mocha',
        colors: {
            primary: '#cba6f7',
            planMode: '#f5c2e7',
            selection: '#89b4fa',
            thinking: '#f5c2e7',
            success: '#a6e3a1',
            error: '#f38ba8',
            info: '#89dceb',
            background: '#1e1e2e',
            surface: '#313244',
            dialogSurface: '#181825',
            thinkingBorder: '#45475a',
            dimSeparator: '#585b70',
        },
    },
    {
        name: 'Solarized Dark',
        colors: {
            primary: '#268bd2',
            planMode: '#d33682',
            selection: '#2aa198',
            thinking: '#6c71c4',
            success: '#859900',
            error: '#dc322f',
            info: '#2aa198',
            background: '#002b36',
            surface: '#073642',
            dialogSurface: '#00212b',
            thinkingBorder: '#0d4654',
            dimSeparator: '#1a5a6a',
        },
    },
    {
        name: 'Monokai Pro',
        colors: {
            primary: '#a9dc76',
            planMode: '#ab9df2',
            selection: '#ffd866',
            thinking: '#ab9df2',
            success: '#a9dc76',
            error: '#ff6188',
            info: '#78dce8',
            background: '#2d2a2e',
            surface: '#3a3a3c',
            dialogSurface: '#221f22',
            thinkingBorder: '#4a4750',
            dimSeparator: '#5b5861',
        },
    },
    {
        name: 'Ayu Dark',
        colors: {
            primary: '#ffb454',
            planMode: '#d2a6ff',
            selection: '#e6b450',
            thinking: '#d2a6ff',
            success: '#7fd962',
            error: '#f07171',
            info: '#39bae6',
            background: '#0d1017',
            surface: '#131721',
            dialogSurface: '#090d12',
            thinkingBorder: '#1e2230',
            dimSeparator: '#2d3347',
        },
    },
    {
        name: 'Everforest',
        colors: {
            primary: '#a7c080',
            planMode: '#d699b6',
            selection: '#7fbbb3',
            thinking: '#d699b6',
            success: '#a7c080',
            error: '#e67e80',
            info: '#7fbbb3',
            background: '#272e33',
            surface: '#2e383c',
            dialogSurface: '#1e2428',
            thinkingBorder: '#3d484d',
            dimSeparator: '#4f585e',
        },
    },
    {
        name: 'Palenight',
        colors: {
            primary: '#82aaff',
            planMode: '#c792ea',
            selection: '#82aaff',
            thinking: '#c792ea',
            success: '#c3e88d',
            error: '#f07178',
            info: '#89ddff',
            background: '#292d3e',
            surface: '#32374d',
            dialogSurface: '#1e2233',
            thinkingBorder: '#444267',
            dimSeparator: '#676e95',
        },
    },
    {
        name: 'One Dark Pro',
        colors: {
            primary: '#61afef',
            planMode: '#c678dd',
            selection: '#61afef',
            thinking: '#c678dd',
            success: '#98c379',
            error: '#e06c75',
            info: '#56b6c2',
            background: '#282c34',
            surface: '#31353f',
            dialogSurface: '#21252b',
            thinkingBorder: '#3e4451',
            dimSeparator: '#4b5263',
        },
    },
    {
        name: 'Cyberpunk',
        colors: {
            primary: '#00fff5',
            planMode: '#ff00a0',
            selection: '#00fff5',
            thinking: '#ff00a0',
            success: '#00ff41',
            error: '#ff0055',
            info: '#00fff5',
            background: '#0d0221',
            surface: '#130a2a',
            dialogSurface: '#080118',
            thinkingBorder: '#2a0a4a',
            dimSeparator: '#3d1466',
        },
    },
    {
        name: 'Synthwave',
        colors: {
            primary: '#ff7edb',
            planMode: '#b893ff',
            selection: '#ff7edb',
            thinking: '#b893ff',
            success: '#72f1b8',
            error: '#fe4450',
            info: '#36f9f6',
            background: '#262335',
            surface: '#2a2139',
            dialogSurface: '#1a1626',
            thinkingBorder: '#3f2d5f',
            dimSeparator: '#614f82',
        },
    },
    {
        name: 'Rosé Pine',
        colors: {
            primary: '#ebbcba',
            planMode: '#c4a7e7',
            selection: '#9ccfd8',
            thinking: '#c4a7e7',
            success: '#31748f',
            error: '#eb6f92',
            info: '#9ccfd8',
            background: '#191724',
            surface: '#26233a',
            dialogSurface: '#111019',
            thinkingBorder: '#403d52',
            dimSeparator: '#524f67',
        },
    },
    {
        name: 'Kanagawa',
        colors: {
            primary: '#7e9cd8',
            planMode: '#957fb8',
            selection: '#7fb4ca',
            thinking: '#957fb8',
            success: '#76946a',
            error: '#c34043',
            info: '#7fb4ca',
            background: '#1f1f28',
            surface: '#2a2a37',
            dialogSurface: '#16161d',
            thinkingBorder: '#363646',
            dimSeparator: '#54546d',
        },
    },
    {
        name: 'Midnight Ocean',
        colors: {
            primary: '#64d8f5',
            planMode: '#a78bfa',
            selection: '#64d8f5',
            thinking: '#a78bfa',
            success: '#6ee7b7',
            error: '#f87171',
            info: '#38bdf8',
            background: '#020c18',
            surface: '#041428',
            dialogSurface: '#010810',
            thinkingBorder: '#0a2a4a',
            dimSeparator: '#103a60',
        },
    },
    {
        name: 'Ember',
        colors: {
            primary: '#ff9f43',
            planMode: '#ee5a24',
            selection: '#feca57',
            thinking: '#ee5a24',
            success: '#55efc4',
            error: '#ff4757',
            info: '#ff9f43',
            background: '#1a0a00',
            surface: '#2d1500',
            dialogSurface: '#120700',
            thinkingBorder: '#4a2200',
            dimSeparator: '#6b3300',
        },
    },
    {
        name: 'Forest',
        colors: {
            primary: '#4ec9a0',
            planMode: '#82d9a5',
            selection: '#4ec9a0',
            thinking: '#82d9a5',
            success: '#4ec9a0',
            error: '#f05e5e',
            info: '#7ad4c5',
            background: '#0e1a13',
            surface: '#162419',
            dialogSurface: '#090f0c',
            thinkingBorder: '#2a4230',
            dimSeparator: '#3d5f47',
        },
    },
    {
        name: 'Deep Space',
        colors: {
            primary: '#9d7cff',
            planMode: '#e07bff',
            selection: '#7caaff',
            thinking: '#e07bff',
            success: '#7cffb0',
            error: '#ff6b8a',
            info: '#7cd4ff',
            background: '#06060f',
            surface: '#0d0d1f',
            dialogSurface: '#030308',
            thinkingBorder: '#1a1a3f',
            dimSeparator: '#2b2b5a',
        },
    },

    // ── Specialty / high-contrast ─────────────────────────────────────────────

    {
        name: 'Matrix',
        colors: {
            primary: '#00ff41',
            planMode: '#00cc33',
            selection: '#00ff41',
            thinking: '#00cc33',
            success: '#00ff41',
            error: '#ff0000',
            info: '#00cc33',
            background: '#000000',
            surface: '#001a00',
            dialogSurface: '#000d00',
            thinkingBorder: '#003300',
            dimSeparator: '#004d00',
        },
    },
    {
        name: 'Amber Terminal',
        colors: {
            primary: '#ffb000',
            planMode: '#ffd040',
            selection: '#ffb000',
            thinking: '#ffd040',
            success: '#ffb000',
            error: '#ff4000',
            info: '#ffd040',
            background: '#0c0800',
            surface: '#1a1200',
            dialogSurface: '#070500',
            thinkingBorder: '#2e2000',
            dimSeparator: '#463000',
        },
    },
    {
        name: 'Phosphor Green',
        colors: {
            primary: '#33ff33',
            planMode: '#99ff99',
            selection: '#66ff66',
            thinking: '#99ff99',
            success: '#33ff33',
            error: '#ff3333',
            info: '#66ff66',
            background: '#001100',
            surface: '#002200',
            dialogSurface: '#000a00',
            thinkingBorder: '#004400',
            dimSeparator: '#006600',
        },
    },
    {
        name: 'High Contrast',
        colors: {
            primary: '#ffff00',
            planMode: '#00ffff',
            selection: '#ffffff',
            thinking: '#00ffff',
            success: '#00ff00',
            error: '#ff0000',
            info: '#00ffff',
            background: '#000000',
            surface: '#111111',
            dialogSurface: '#000000',
            thinkingBorder: '#333333',
            dimSeparator: '#555555',
        },
    },

    // ── Pastel / soft ────────────────────────────────────────────────────────

    {
        name: 'Cotton Candy',
        colors: {
            primary: '#f77ebe',
            planMode: '#c9a0f7',
            selection: '#7eb8f7',
            thinking: '#c9a0f7',
            success: '#a0f7c9',
            error: '#f7a0a0',
            info: '#a0d4f7',
            background: '#1a1320',
            surface: '#261c2e',
            dialogSurface: '#110d16',
            thinkingBorder: '#3d2e4a',
            dimSeparator: '#594466',
        },
    },
    {
        name: 'Lavender Fields',
        colors: {
            primary: '#b39ddb',
            planMode: '#e1bee7',
            selection: '#9fa8da',
            thinking: '#e1bee7',
            success: '#a5d6a7',
            error: '#ef9a9a',
            info: '#80cbc4',
            background: '#1a1625',
            surface: '#231f33',
            dialogSurface: '#13101c',
            thinkingBorder: '#382f4d',
            dimSeparator: '#4a3f66',
        },
    },
    {
        name: 'Peach Fuzz',
        colors: {
            primary: '#ffab91',
            planMode: '#f48fb1',
            selection: '#ffcc80',
            thinking: '#f48fb1',
            success: '#a5d6a7',
            error: '#ef9a9a',
            info: '#80deea',
            background: '#1a1210',
            surface: '#261a16',
            dialogSurface: '#110c0a',
            thinkingBorder: '#40281f',
            dimSeparator: '#5a3a2e',
        },
    },
    {
        name: 'Mint Julep',
        colors: {
            primary: '#80cbc4',
            planMode: '#a5d6a7',
            selection: '#80cbc4',
            thinking: '#a5d6a7',
            success: '#80cbc4',
            error: '#ef9a9a',
            info: '#80deea',
            background: '#0f1a18',
            surface: '#172624',
            dialogSurface: '#0a1210',
            thinkingBorder: '#1e3d38',
            dimSeparator: '#2e5a52',
        },
    },

    // ── Earth / natural ──────────────────────────────────────────────────────

    {
        name: 'Desert Dusk',
        colors: {
            primary: '#e8a87c',
            planMode: '#c97b9e',
            selection: '#e8c97c',
            thinking: '#c97b9e',
            success: '#8eb897',
            error: '#d45f5f',
            info: '#7cb8c9',
            background: '#1a1208',
            surface: '#261a0c',
            dialogSurface: '#110c05',
            thinkingBorder: '#3d2e18',
            dimSeparator: '#5a4426',
        },
    },
    {
        name: 'Sahara',
        colors: {
            primary: '#d4a853',
            planMode: '#b07030',
            selection: '#d4c053',
            thinking: '#b07030',
            success: '#7a9e6a',
            error: '#c0504a',
            info: '#5a9ab0',
            background: '#180f04',
            surface: '#261808',
            dialogSurface: '#0f0a02',
            thinkingBorder: '#3d2a10',
            dimSeparator: '#5a3e1a',
        },
    },
    {
        name: 'Slate',
        colors: {
            primary: '#94a3b8',
            planMode: '#a78bfa',
            selection: '#7dd3fc',
            thinking: '#a78bfa',
            success: '#6ee7b7',
            error: '#fca5a5',
            info: '#67e8f9',
            background: '#0f172a',
            surface: '#1e293b',
            dialogSurface: '#0a1020',
            thinkingBorder: '#334155',
            dimSeparator: '#475569',
        },
    },

    // ── Vivid / neon ─────────────────────────────────────────────────────────

    {
        name: 'Neon Tropics',
        colors: {
            primary: '#00f5a0',
            planMode: '#fc4cfc',
            selection: '#00f5a0',
            thinking: '#fc4cfc',
            success: '#00f5a0',
            error: '#ff3d5a',
            info: '#00d9e8',
            background: '#04100c',
            surface: '#081c14',
            dialogSurface: '#020908',
            thinkingBorder: '#0d3325',
            dimSeparator: '#134d38',
        },
    },
    {
        name: 'Electric Blue',
        colors: {
            primary: '#00bfff',
            planMode: '#7b68ee',
            selection: '#00bfff',
            thinking: '#7b68ee',
            success: '#00fa9a',
            error: '#ff4444',
            info: '#00bfff',
            background: '#00080f',
            surface: '#001020',
            dialogSurface: '#00050c',
            thinkingBorder: '#001f3d',
            dimSeparator: '#002d5a',
        },
    },
    {
        name: 'Acid',
        colors: {
            primary: '#cfff04',
            planMode: '#ff04cf',
            selection: '#04cfff',
            thinking: '#ff04cf',
            success: '#04ff8a',
            error: '#ff2d55',
            info: '#04cfff',
            background: '#0a0a00',
            surface: '#141400',
            dialogSurface: '#060600',
            thinkingBorder: '#282800',
            dimSeparator: '#3d3d00',
        },
    },
    {
        name: 'Vaporwave',
        colors: {
            primary: '#ff71ce',
            planMode: '#b967ff',
            selection: '#01cdfe',
            thinking: '#b967ff',
            success: '#05ffa1',
            error: '#ff3864',
            info: '#01cdfe',
            background: '#0d0221',
            surface: '#170935',
            dialogSurface: '#080116',
            thinkingBorder: '#2d1068',
            dimSeparator: '#41187a',
        },
    },

    // ── Monochrome ────────────────────────────────────────────────────────────

    {
        name: 'Charcoal',
        colors: {
            primary: '#d0d0d0',
            planMode: '#a0a0a0',
            selection: '#e8e8e8',
            thinking: '#b8b8b8',
            success: '#c8c8c8',
            error: '#f0f0f0',
            info: '#d8d8d8',
            background: '#111111',
            surface: '#1e1e1e',
            dialogSurface: '#0a0a0a',
            thinkingBorder: '#303030',
            dimSeparator: '#444444',
        },
    },
    {
        name: 'Ghost',
        colors: {
            primary: '#e8e8f0',
            planMode: '#b8b8d0',
            selection: '#c8c8e8',
            thinking: '#a8a8c8',
            success: '#98d8b0',
            error: '#e89898',
            info: '#98c8e8',
            background: '#0e0e14',
            surface: '#16161e',
            dialogSurface: '#090910',
            thinkingBorder: '#26263a',
            dimSeparator: '#36364e',
        },
    },

    // ── Pop culture inspired ──────────────────────────────────────────────────

    {
        name: 'C64',
        colors: {
            primary: '#7b70de',
            planMode: '#b8b8ff',
            selection: '#9d9dff',
            thinking: '#c4c4ff',
            success: '#7b70de',
            error: '#ff6464',
            info: '#9d9dff',
            background: '#3333aa',
            surface: '#4040bb',
            dialogSurface: '#2828a0',
            thinkingBorder: '#5555cc',
            dimSeparator: '#6666dd',
        },
    },
    {
        name: 'Terminal Green (VT100)',
        colors: {
            primary: '#22dd22',
            planMode: '#55ff55',
            selection: '#44ee44',
            thinking: '#55ff55',
            success: '#22dd22',
            error: '#dd2222',
            info: '#44ee44',
            background: '#010d01',
            surface: '#021502',
            dialogSurface: '#000800',
            thinkingBorder: '#042204',
            dimSeparator: '#073307',
        },
    },

    // ── Seasonal / atmospheric ────────────────────────────────────────────────

    {
        name: 'Aurora',
        colors: {
            primary: '#4dffa6',
            planMode: '#c580ff',
            selection: '#47d4ff',
            thinking: '#c580ff',
            success: '#4dffa6',
            error: '#ff5a7d',
            info: '#47d4ff',
            background: '#030d14',
            surface: '#061828',
            dialogSurface: '#02080e',
            thinkingBorder: '#0a2c44',
            dimSeparator: '#10436a',
        },
    },
    {
        name: 'Winter Solstice',
        colors: {
            primary: '#a8c8e8',
            planMode: '#c8a8e8',
            selection: '#88b8e8',
            thinking: '#b8a8d8',
            success: '#88c8b8',
            error: '#e87888',
            info: '#88b8d8',
            background: '#0a0e18',
            surface: '#10162a',
            dialogSurface: '#060910',
            thinkingBorder: '#1a2438',
            dimSeparator: '#28384e',
        },
    },
    {
        name: 'Autumn',
        colors: {
            primary: '#e8962a',
            planMode: '#c84848',
            selection: '#d8c040',
            thinking: '#c84848',
            success: '#7ab040',
            error: '#c83030',
            info: '#5090b0',
            background: '#100c04',
            surface: '#1e1608',
            dialogSurface: '#0a0802',
            thinkingBorder: '#362810',
            dimSeparator: '#503c18',
        },
    },
    {
        name: 'Spring Bloom',
        colors: {
            primary: '#f4a8c8',
            planMode: '#c8a0f4',
            selection: '#a8d4f4',
            thinking: '#c8a0f4',
            success: '#a0d8a0',
            error: '#f48888',
            info: '#88cce8',
            background: '#140c14',
            surface: '#200e20',
            dialogSurface: '#0e080e',
            thinkingBorder: '#381e38',
            dimSeparator: '#502e50',
        },
    },
    {
        name: 'Summer Heat',
        colors: {
            primary: '#ffd23f',
            planMode: '#ff6b6b',
            selection: '#ffe66d',
            thinking: '#ff6b6b',
            success: '#4ecdc4',
            error: '#ff4444',
            info: '#45b7d1',
            background: '#120800',
            surface: '#1e0e00',
            dialogSurface: '#0c0500',
            thinkingBorder: '#3a1e00',
            dimSeparator: '#562d00',
        },
    },
]

export const DEFAULT_THEME = THEMES.find((theme) => theme.name === 'Obsidian')
